Add remove
nevisende/todo pull request #3
Opened 2021-12-02 07:58 UTC by nevisende

### List of things I've done:
- I removed all hardcoded items from the tasks array.
- I created a JavaScript file for the new functionality.
- I implemented the `addToDo ` function for adding a new task (add a new element to the array).
- I implemented the `deleteToDoList ` function for deleting a task (remove an element from the array).
- I implement the `deleteAllChecked ` function for the "Clear all completed" button (used filter() method).
- By default new tasks have the property `checked `set to `false `and the property index set to the value of the last item's index number +1. 
- I pick a better way than deleting a task to update all remaining items' indexes.
- All changes to the To-Do List is saved in local storage.

2021-12-02 09:55 UTC, henatan99 requested changes
Hi @nevisende , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [x] I think you should update your readme with at least a minimal description and other relevant info like setup, installation and usage instructions, and your professional network links.  I suggest you use the Microverse [readme template](https://github.com/microverseinc/readme-template). :pray: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 09:55 UTC, henatan99 commented on src/main.js
> +}
- [ ] Everything is working very fine. But when a todo item is deleted or when all checked todo items are deleted the indexes should be updated to ordered indexes. For example, if I have three todos with indexes of 1, 2, and 3, and if I delete the todo item with index 2, I should get filtered todos with indexes of 1 and 2. Kindly fix this issue and you are good to go. :pray: 

![Screenshot from 2021-12-02 12-46-57](https://user-images.githubusercontent.com/64894927/144398824-28ea320d-f9d4-4e7c-9b8b-8345b764a020.png)

2021-12-02 12:16 UTC, nevisende commented on src/main.js
> +}
Yes, I chose this method on purpose, otherwise, I would have to apply an algorithm that would slow down the performance, such as checking the entire list after a deleted element and updating it again. Instead, just following the index of the last element from the localStorage and continuing it allows me to get a more unique id.

2021-12-02 13:18 UTC, nevisende commented on src/main.js
> +}
I made a change as you said, but as I said, the algorithm I applied before the change was more efficient.

2021-12-02 14:37 UTC, D4nielJ commented
Hi @nevisende, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no new commits. Please make sure to follow the recommendations of the previous code Reviewer regarding the README file and the To-do list code and ask for a new code review then.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-12-02 16:25 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Furkan, 
 ### Thank you fr working on the changes suggested. :ok_hand:
## To Improve 🙏
- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-02 16:25 UTC, SajjadAhmad14 commented on README.md
> +# My Portfolio
README file should be professional and updated because it's the first place user looks at when using your project. Please add the project name, project description, and instructions to set it up locally.

2021-12-02 16:42 UTC, nevisende commented on README.md
> +# My Portfolio
Your are right but this is not requirement on the project description. But now I changed it.

2021-12-02 16:52 UTC, helman101 requested changes
# STATUS: CHANGES REQUIRED ♻️ 🔴 

Hi @nevisende 👋, 

Great work on making the changes requested by a previous reviewer 👏 👏👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🌟 

- Nice job adding some content to your README file.

## Required Changes ♻️

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 16:52 UTC, helman101 commented on README.md
> +
- [ ] You still don't see any description of the project, what were the goals for this project, what did you archive, why did you build this in the first place, kindly add a short description of what is the project about 😄

2021-12-02 16:52 UTC, helman101 commented on README.md
> +
- [ ] Please add instructions on how to install and run this project, you should explain the instructions like if someone that never touched code before was trying to see and run your project 😄

2021-12-02 17:04 UTC, nevisende commented on README.md
> +
What is your aim? What is your aim? What is your aim?

2021-12-02 17:46 UTC, nevisende commented on README.md
> +
If you look at the last commit you can see

2021-12-03 10:04 UTC, bellom commented
Hello 👋,

This is an additional review as a result of the second opinion request.

@nevisende I'm deeply sorry if the emoji was used wrongly 🙏 , the CR was trying to be friendly honestly.
The problem was that the first CR was supposed to mark the review Invalid because your README file wasn't professional, check out Microverse [professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
Screenshot from Project Requirement: 
![image](https://user-images.githubusercontent.com/31897434/144582766-c6f1a2e8-ef47-49c4-bcab-255c05ca2927.png)

PS: The origin of the problem came from your [previous PR's](https://github.com/nevisende/awesome-books/pulls?q=is%3Apr+is%3Aclosed) that was approved without a descriptive README 🤦 .


**Great work making all the necessary corrections from the previous review.** 👍 

To Improve:
You can update your README file with the project setup steps which non-technical individuals can use to set up your app locally. 
Example:
```
- git clone `your repo`
- cd into the folder
- git checkout `branch-name`
- run `npm i`
- run `npm start`
```
I hope this is more clear now.

Because you have implemented all of the requested changes this project is approved now.

You will see changes in your Dashboard in ~1h.

Keep rocking 🚀!

2021-12-03 10:10 UTC, Dipeshtwis approved these changes
# Hi Team, 

### Status: Approved ✔️

:+1:  You have done well implementing the suggested changes. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**_Check the comments under the review_**


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Dipesh Kumar_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 10:10 UTC, Dipeshtwis commented on README.md
> +
[OPTIONAL] [HIGHLY RECOMMENDED]

- I would recommend adding the steps on how to clone and move into the project folder as it is very first step if user wants to run the project locally.

Hint:
```
$ git clone https://github.com/nevisende/todo.git

$ cd todo

and then installing the npm packages
$ npm i or npm install

and then to run the server
$ npm start

```

2021-12-03 10:19 UTC, merged