Testing 2
nevisende/todo pull request #9
Opened 2021-12-09 15:13 UTC by nevisende

We created the ` add-del-update.test.js` file.It contains the following functions:
  - the` updateDescription()` function for editing the task description.
  - the `loopCheckBoxes()` function for updating an item's 'completed' status.
  - the `deleteAllChecked()` function.
 
> We used the mock storage object we have created in Part 1 of this project to mock the localStorage updates.
> Mocked the HTML elements to test DOM manipulation functions.
> We group our tests using the description() method.

2021-12-09 16:34 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @nevisende and @direakanbi,

Good job so far!
✔️ Your code looks neat
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-09 16:34 UTC, TedLivist commented on src/__test__/add-del-update.test.js
> +    __esModule: true,
Please take a look at the image below
- [ ] The seems to be an issue with your test files. None of your tests seem to be passing. Kindly fix this.

![nevis-test](https://user-images.githubusercontent.com/36542986/145437054-2de6ee31-3210-4f94-9863-562d627f7735.jpg)

2021-12-10 07:28 UTC, nevisende commented on src/__test__/add-del-update.test.js
> +    __esModule: true,
Just in case you're right, we tried it on our own computers and didn't find any issues. Then a friend of ours tried it at the morning session meeting and he didn't see any problem in the 'testing-2' branch. I think the problem is with your computer.

2021-12-10 07:36 UTC, TedLivist commented on src/__test__/add-del-update.test.js
> +    __esModule: true,
@nevisende oh yeah? Maybe you're right. As you can see on the bottom left I'm on the `testing-2` branch. In that case, kindly request another review.

2021-12-10 07:48 UTC, Emmyn5600 approved these changes
STATUS: APPROVED :+1: 

Hello, the team @nevisende and @TedLivist   👋🏾 👋🏾 congratulations on implementing all the changes requested by the previous reviewer as well as the project requirements.
![testing-1](https://user-images.githubusercontent.com/55635977/145536759-a9453b11-dcf8-4605-9ae8-5cfdd72a0378.png)

## Optional suggestions

- N/a

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

2021-12-10 07:58 UTC, merged